declare const styles: {
  readonly "responsive": string;
  readonly "embedVideoContainer": string;
  readonly "youtube": string;
  readonly "elevationBase": string;
  readonly "elevationMedium": string;
  readonly "elevationLarge": string;
  readonly "elevationXl": string;
  readonly "elevationXxl": string;
  readonly "boxSuccess": string;
  readonly "boxWarning": string;
  readonly "boxInfo": string;
  readonly "boxError": string;
  readonly "boxNews": string;
  readonly "linkSuccess": string;
  readonly "linkWarning": string;
  readonly "linkInfo": string;
  readonly "linkError": string;
  readonly "linkNews": string;
  readonly "textSuccess": string;
  readonly "textWarning": string;
  readonly "textInfo": string;
  readonly "textError": string;
  readonly "textNews": string;
  readonly "iconSuccess": string;
  readonly "iconWarning": string;
  readonly "iconInfo": string;
  readonly "iconError": string;
  readonly "iconNews": string;
};
export = styles;

