declare const styles: {
  readonly mt2: string
  readonly mt4: string
  readonly mt6: string
  readonly mt8: string
  readonly mt12: string
  readonly mt16: string
  readonly mt24: string
  readonly mt32: string
  readonly mt48: string
  readonly mt64: string
  readonly mt128: string
  readonly mb2: string
  readonly mb4: string
  readonly mb6: string
  readonly mb8: string
  readonly mb12: string
  readonly mb16: string
  readonly mb24: string
  readonly mb32: string
  readonly mb48: string
  readonly mb64: string
  readonly mb128: string
  readonly ml2: string
  readonly ml4: string
  readonly ml6: string
  readonly ml8: string
  readonly ml12: string
  readonly ml16: string
  readonly ml24: string
  readonly ml32: string
  readonly ml48: string
  readonly ml64: string
  readonly ml128: string
  readonly mr2: string
  readonly mr4: string
  readonly mr6: string
  readonly mr8: string
  readonly mr12: string
  readonly mr16: string
  readonly mr24: string
  readonly mr32: string
  readonly mr48: string
  readonly mr64: string
  readonly mr128: string
}
export = styles
